---

- name: "Docker Install"
  hosts: "all"
  become: true
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
  vars:
    docker__edition: "ce"
    docker__version: "18.06.1"

  tasks:
  - name: Ensure that docker is started
    service:
      name: docker
      state: started
